import { Command } from "commander";
import { planExtensionInstall, applyExtensionInstall } from "../extensions/engine";
import { FIRST_PARTY_EXTENSIONS } from "../extensions/first-party";
import { loadPluginManifest } from "../extensions/plugins";
import { applyExtensionRemoval, planExtensionRemoval } from "../extensions/remove";
import type { ExtensionManifest } from "../extensions/types";
import { loadProjectManifest } from "../project/manifest";
import { loadProjectState } from "../project/state";

type CommonOptions = { directory?: string; json?: boolean; dryRun?: boolean; allowHooks?: boolean };
const directory = (options: CommonOptions) => options.directory ?? process.cwd();
function print(value: unknown, json?: boolean): void { if (json) console.log(JSON.stringify(value, null, 2)); else if (Array.isArray(value)) for (const item of value) console.log(typeof item === "string" ? item : JSON.stringify(item)); else console.log(typeof value === "string" ? value : JSON.stringify(value, null, 2)); }
function fail(error: unknown): void { console.error(error instanceof Error ? error.message : String(error)); process.exitCode = 1; }
function installLike(name: "add" | "upgrade"): Command { return pluginCommand.command(name).argument("<specifier>").option("-d, --directory <path>").option("--dry-run").option("--allow-hooks").option("--json").action((specifier: string, options: CommonOptions) => { try { const item = loadPluginManifest(directory(options), specifier, { allowHooks: options.allowHooks }); const plan = planExtensionInstall({ projectDirectory: directory(options), requested: [item.id], registry: { ...FIRST_PARTY_EXTENSIONS, [item.id]: item } }); if (!options.dryRun) applyExtensionInstall(plan); print({ dryRun: Boolean(options.dryRun), plugin: `${item.id}@${item.version}`, actions: plan.actions, warnings: plan.warnings }, options.json); } catch (error) { fail(error); } }); }
export const pluginCommand = new Command("plugin").description("Manage validated LaunchStack extension manifests");
pluginCommand.command("list").option("-d, --directory <path>").option("--json").action((options: CommonOptions) => { try { const manifest = loadProjectManifest(directory(options)); const state = loadProjectState(directory(options), { templateVersion: manifest.project.templateVersion, cliVersion: "unknown" }); const plugins = Object.values(state.extensions).filter((item) => item.kind === "plugin").sort((a, b) => a.id.localeCompare(b.id)); print(options.json ? plugins : plugins.map((item) => `${item.id}\t${item.version}`), options.json); } catch (error) { fail(error); } });
pluginCommand.command("validate").argument("<specifier>").option("-d, --directory <path>").option("--allow-hooks").option("--json").action((specifier: string, options: CommonOptions) => { try { print(loadPluginManifest(directory(options), specifier, { allowHooks: options.allowHooks }), options.json); } catch (error) { fail(error); } });
installLike("add"); installLike("upgrade");
pluginCommand.command("remove").argument("<plugin-id>").option("-d, --directory <path>").option("--manifest <path>").option("--dry-run").option("--json").action((pluginId: string, options: CommonOptions & { manifest?: string }) => { try { const projectDirectory = directory(options); const manifest = loadProjectManifest(projectDirectory); const state = loadProjectState(projectDirectory, { templateVersion: manifest.project.templateVersion, cliVersion: "unknown" }); const installed = state.extensions[pluginId]; if (!installed || installed.kind !== "plugin") throw new Error(`${pluginId} is not an installed plugin.`); let item: ExtensionManifest; if (options.manifest) { item = loadPluginManifest(projectDirectory, options.manifest, { allowHooks: true }); if (item.id !== pluginId) throw new Error(`Manifest ID ${item.id} does not match installed plugin ${pluginId}.`); } else item = { schemaVersion: 1, id: pluginId, version: installed.version, kind: "plugin", displayName: pluginId, supportedLaunchStack: ">=2 <4" }; const plan = planExtensionRemoval({ projectDirectory, extension: item }); if (!options.dryRun) applyExtensionRemoval(plan); print({ dryRun: Boolean(options.dryRun), plugin: pluginId, actions: plan.mutations.map((mutation) => ({ type: mutation.type, path: mutation.path })), warnings: plan.warnings }, options.json); } catch (error) { fail(error); } });
