import { Command } from "commander";
import { detectManagedDrift, loadProjectState } from "../project/state";
import { loadProjectManifest } from "../project/manifest";
import { applyReconciliation, planReconciliation } from "../project/reconcile";
import { applyUpgrade, planUpgrade } from "../project/upgrade";
function fail(error: unknown): void { console.error(error instanceof Error ? error.message : String(error)); process.exitCode = 1; }
function printPlan(plan: ReturnType<typeof planReconciliation>, json?: boolean): void { if (json) { console.log(JSON.stringify(plan, null, 2)); return; } for (const action of plan.actions) console.log(`${action.destructive ? "DESTRUCTIVE" : "PLAN"} ${action.kind} ${action.target}: ${action.detail}`); for (const warning of plan.warnings) console.warn(`WARN ${warning}`); for (const conflict of plan.conflicts) console.error(`CONFLICT ${conflict}`); if (!plan.actions.length && !plan.conflicts.length) console.log("Project matches declared LaunchStack state."); }
export const diffCommand = new Command("diff").description("Show drift in LaunchStack-managed project files").option("-d, --directory <path>").option("--json").action((options: { directory?: string; json?: boolean }) => { try { const dir = options.directory ?? process.cwd(); const manifest = loadProjectManifest(dir); const drift = detectManagedDrift(dir, loadProjectState(dir, { templateVersion: manifest.project.templateVersion, cliVersion: "unknown" })); if (options.json) console.log(JSON.stringify(drift, null, 2)); else for (const item of drift) console.log(`${item.kind.toUpperCase()} ${item.path}`); if (drift.some((item) => item.kind === "modified" || item.kind === "missing")) process.exitCode = 1; } catch (error) { fail(error); } });
export const planCommand = new Command("plan").description("Plan reconciliation from launchstack.json").option("-d, --directory <path>").option("--json").action((options: { directory?: string; json?: boolean }) => { try { const plan = planReconciliation(options.directory ?? process.cwd()); printPlan(plan, options.json); if (plan.conflicts.length) process.exitCode = 1; } catch (error) { fail(error); } });
const applyAction = (options: { directory?: string; json?: boolean; allowRemove?: boolean }) => { try { const plan = applyReconciliation({ projectDirectory: options.directory ?? process.cwd(), allowRemove: options.allowRemove }); printPlan(plan, options.json); if (plan.conflicts.length) process.exitCode = 1; } catch (error) { fail(error); } };
export const applyCommand = new Command("apply").description("Apply declared LaunchStack state").option("-d, --directory <path>").option("--allow-remove").option("--json").action(applyAction);
export const reconcileCommand = new Command("reconcile").description("Reconcile project state with launchstack.json").option("-d, --directory <path>").option("--allow-remove").option("--json").action(applyAction);
export const upgradeCommand = new Command("upgrade").description("Safely adopt or upgrade a LaunchStack project").option("-d, --directory <path>").option("--plan").option("--json").action((options: { directory?: string; plan?: boolean; json?: boolean }) => { try { const plan = planUpgrade(options.directory ?? process.cwd()); if (!options.plan && !plan.conflicts.length) applyUpgrade(plan); const output = { dryRun: Boolean(options.plan), fromVersion: plan.fromVersion, toVersion: plan.toVersion, actions: plan.actions, conflicts: plan.conflicts }; if (options.json) console.log(JSON.stringify(output, null, 2)); else { for (const action of plan.actions) console.log(`${options.plan ? "PLAN" : "APPLY"} ${action.kind} ${action.target}: ${action.detail}`); for (const conflict of plan.conflicts) console.error(`CONFLICT ${conflict}`); } if (plan.conflicts.length) process.exitCode = 1; } catch (error) { fail(error); } });
