import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { createProjectManifest, loadProjectManifest, serializeProjectManifest } from "./manifest";
import { resolveProjectPath } from "./paths";
import { hashFile, loadProjectState, serializeProjectState } from "./state";
import { applyFileMutations, withTrackedMutations } from "./transaction";
import { emptyProjectState, type FileMutation, type LifecycleAction, type ProjectManifest, type ProjectState } from "./types";
import { currentLaunchStackVersion } from "../version";
export const V3_TEMPLATE_VERSION = "3.0.0";
export type UpgradePlan = { projectDirectory: string; fromVersion: string; toVersion: string; actions: LifecycleAction[]; conflicts: string[]; mutations: FileMutation[]; nextManifest: ProjectManifest; nextState: ProjectState };
function readText(projectDirectory: string, path: string) { const absolute = resolveProjectPath(projectDirectory, path); if (!existsSync(absolute)) throw new Error(`Expected project file is missing: ${path}`); return { content: readFileSync(absolute, "utf8"), hash: hashFile(absolute) }; }
function inferLegacyProject(projectDirectory: string): { name: string; version: string } { const packagePath = resolveProjectPath(projectDirectory, "package.json"); if (!existsSync(packagePath)) throw new Error("No launchstack.json or package.json was found; this does not look like a LaunchStack project."); const parsed = JSON.parse(readFileSync(packagePath, "utf8")) as { name?: unknown; version?: unknown }; if (typeof parsed.name !== "string" || typeof parsed.version !== "string") throw new Error("Legacy package.json does not contain a valid name/version."); if (!existsSync(resolveProjectPath(projectDirectory, "src/app.ts")) || !existsSync(resolveProjectPath(projectDirectory, "src/routes/index.ts"))) throw new Error("Legacy project is missing LaunchStack architecture files."); if (!/^2\./.test(parsed.version) && !/^3\./.test(parsed.version)) throw new Error(`Unsupported legacy template version: ${parsed.version}`); return { name: parsed.name, version: parsed.version }; }
function patchRoutes(content: string): string { if (content.includes("registerGeneratedRoutes")) return content; const anchor = /import \{ readinessRoutes \} from ["']\.\/readiness["'];/; if (!anchor.test(content)) throw new Error("Cannot safely upgrade src/routes/index.ts: readiness import anchor not found."); let next = content.replace(anchor, (match) => `${match}\nimport { registerGeneratedRoutes } from "./launchstack.generated";`); const closing = next.lastIndexOf("}\n"); if (closing < 0) throw new Error("Cannot safely upgrade src/routes/index.ts: function boundary not found."); return `${next.slice(0, closing)}\n  await registerGeneratedRoutes(app);\n${next.slice(closing)}`; }
function patchApp(content: string): string { if (content.includes("registerLaunchStackCapabilities")) return content; const anchor = /import \{ registerPlugins \} from ["']\.\/plugins["'];/; if (!anchor.test(content)) throw new Error("Cannot safely upgrade src/app.ts: plugin import anchor not found."); let next = content.replace(anchor, (match) => `${match}\nimport { registerLaunchStackCapabilities } from "./launchstack/capabilities";`); const call = "  await registerPlugins(app);"; if (!next.includes(call)) throw new Error("Cannot safely upgrade src/app.ts: plugin registration anchor not found."); return next.replace(call, `${call}\n  await registerLaunchStackCapabilities(app);`); }
function metadataMutation(projectDirectory: string, path: string, content: string): FileMutation { const absolute = resolveProjectPath(projectDirectory, path); return { type: "write", path, content, owner: "launchstack:metadata", version: currentLaunchStackVersion(), expectedSha256: existsSync(absolute) ? hashFile(absolute) : null }; }
export function planUpgrade(projectDirectoryInput: string): UpgradePlan {
  const projectDirectory = resolve(projectDirectoryInput); const hasManifest = existsSync(resolveProjectPath(projectDirectory, "launchstack.json")); const legacy = hasManifest ? null : inferLegacyProject(projectDirectory); const manifest = hasManifest ? loadProjectManifest(projectDirectory) : createProjectManifest({ name: legacy?.name ?? "legacy-project", templateVersion: legacy?.version ?? "2.0.0" }); const fromVersion = manifest.project.templateVersion; const state = hasManifest ? loadProjectState(projectDirectory, { templateVersion: fromVersion, cliVersion: currentLaunchStackVersion() }) : emptyProjectState(fromVersion, currentLaunchStackVersion()); const actions: LifecycleAction[] = []; const conflicts: string[] = []; const mutations: FileMutation[] = [];
  if (!/^2\./.test(fromVersion) && fromVersion !== V3_TEMPLATE_VERSION) conflicts.push(`No ordered migration is registered from template ${fromVersion}.`);
  const generatedRoutesPath = "src/routes/launchstack.generated.ts"; if (!existsSync(resolveProjectPath(projectDirectory, generatedRoutesPath))) { mutations.push({ type: "write", path: generatedRoutesPath, content: `import type { FastifyInstance } from "fastify";\n\n/* launchstack-routes: [] */\nexport async function registerGeneratedRoutes(app: FastifyInstance): Promise<void> { void app; }\n`, owner: "launchstack:core", version: V3_TEMPLATE_VERSION, expectedSha256: null }); actions.push({ id: "v3:route-registry", kind: "write", target: generatedRoutesPath, detail: "create generated route ownership boundary" }); }
  const capabilitiesPath = "src/launchstack/capabilities/index.ts"; if (!existsSync(resolveProjectPath(projectDirectory, capabilitiesPath))) { mutations.push({ type: "write", path: capabilitiesPath, content: `import type { FastifyInstance } from "fastify";\nexport async function registerLaunchStackCapabilities(app: FastifyInstance): Promise<void> { void app; }\n`, owner: "launchstack:core", version: V3_TEMPLATE_VERSION, expectedSha256: null }); actions.push({ id: "v3:capability-registry", kind: "write", target: capabilitiesPath, detail: "create capability ownership boundary" }); }
  try { const routes = readText(projectDirectory, "src/routes/index.ts"); const next = patchRoutes(routes.content); if (next !== routes.content) { mutations.push({ type: "write", path: "src/routes/index.ts", content: next, owner: "launchstack:metadata", version: V3_TEMPLATE_VERSION, expectedSha256: routes.hash }); actions.push({ id: "v3:routes-wire", kind: "write", target: "src/routes/index.ts", detail: "wire generated route registry" }); } } catch (error) { conflicts.push(error instanceof Error ? error.message : String(error)); }
  try { const app = readText(projectDirectory, "src/app.ts"); const next = patchApp(app.content); if (next !== app.content) { mutations.push({ type: "write", path: "src/app.ts", content: next, owner: "launchstack:metadata", version: V3_TEMPLATE_VERSION, expectedSha256: app.hash }); actions.push({ id: "v3:capabilities-wire", kind: "write", target: "src/app.ts", detail: "wire capability registry" }); } } catch (error) { conflicts.push(error instanceof Error ? error.message : String(error)); }
  const nextManifest = structuredClone(manifest); nextManifest.project.templateVersion = V3_TEMPLATE_VERSION; const nextState = withTrackedMutations(state, mutations); nextState.templateVersion = V3_TEMPLATE_VERSION; nextState.cliVersion = currentLaunchStackVersion(); nextState.updatedAt = new Date().toISOString(); if (!hasManifest || fromVersion !== V3_TEMPLATE_VERSION) actions.push({ id: "v3:metadata", kind: "upgrade", target: "launchstack.json", detail: `${fromVersion} -> ${V3_TEMPLATE_VERSION}` });
  return { projectDirectory, fromVersion, toVersion: V3_TEMPLATE_VERSION, actions, conflicts, mutations, nextManifest, nextState };
}
export function applyUpgrade(plan: UpgradePlan): ProjectState { if (plan.conflicts.length) throw new Error(`Upgrade conflicts: ${plan.conflicts.join("; ")}`); return applyFileMutations({ projectDirectory: plan.projectDirectory, mutations: [...plan.mutations, metadataMutation(plan.projectDirectory, "launchstack.json", serializeProjectManifest(plan.nextManifest)), metadataMutation(plan.projectDirectory, ".launchstack/state.json", serializeProjectState(plan.nextState))], state: existsSync(resolveProjectPath(plan.projectDirectory, ".launchstack/state.json")) ? loadProjectState(plan.projectDirectory) : emptyProjectState(plan.fromVersion, currentLaunchStackVersion()), nextState: plan.nextState }); }
