import { createHash } from "node:crypto";
export type OpenApiSchema = { type?: string | string[]; nullable?: boolean; enum?: Array<string | number | boolean | null>; properties?: Record<string, OpenApiSchema>; required?: string[]; items?: OpenApiSchema; additionalProperties?: boolean | OpenApiSchema; oneOf?: OpenApiSchema[]; anyOf?: OpenApiSchema[]; allOf?: OpenApiSchema[]; $ref?: string };
export type OpenApiParameter = { name: string; in: "path" | "query" | "header" | "cookie"; required?: boolean; schema?: OpenApiSchema };
export type OpenApiOperation = { operationId?: string; parameters?: OpenApiParameter[]; requestBody?: { required?: boolean; content?: Record<string, { schema?: OpenApiSchema }> }; responses?: Record<string, { description?: string; content?: Record<string, { schema?: OpenApiSchema }> }> };
export type OpenApiDocument = { openapi: string; info?: { title?: string; version?: string }; paths: Record<string, Record<string, OpenApiOperation | unknown>>; components?: { schemas?: Record<string, OpenApiSchema> } };
const METHODS = new Set(["get", "post", "put", "patch", "delete", "head", "options"]);
const object = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === "object" && !Array.isArray(value);
export function parseOpenApiDocument(value: unknown): OpenApiDocument { if (!object(value) || typeof value.openapi !== "string" || !object(value.paths)) throw new Error("OpenAPI document must contain an openapi version and paths object."); return value as OpenApiDocument; }
function sanitize(input: string): string { const words = input.replace(/[^A-Za-z0-9_$]+/g, " ").trim().split(/\s+/).filter(Boolean); let result = words.map((word, index) => index === 0 ? word.charAt(0).toLowerCase() + word.slice(1) : word.charAt(0).toUpperCase() + word.slice(1)).join(""); if (!result) result = "operation"; if (/^[0-9]/.test(result)) result = `op${result}`; return result.replace(/[^A-Za-z0-9_$]/g, ""); }
export type ParsedOperation = { method: string; path: string; name: string; operation: OpenApiOperation };
export function collectOperations(document: OpenApiDocument): ParsedOperation[] { const raw: Array<Omit<ParsedOperation, "name"> & { preferredName: string }> = []; for (const path of Object.keys(document.paths).sort()) { const item = document.paths[path] ?? {}; for (const method of Object.keys(item).sort()) { if (!METHODS.has(method.toLowerCase())) continue; const operation = item[method]; if (!object(operation)) continue; const typed = operation as OpenApiOperation; raw.push({ method: method.toUpperCase(), path, operation: typed, preferredName: sanitize(typed.operationId ?? `${method}-${path.replace(/[{}]/g, "")}`) }); } } const counts = new Map<string, number>(); for (const item of raw) counts.set(item.preferredName, (counts.get(item.preferredName) ?? 0) + 1); return raw.map(({ preferredName, ...item }) => ({ ...item, name: (counts.get(preferredName) ?? 0) > 1 ? `${preferredName}_${createHash("sha256").update(`${item.method} ${item.path}`).digest("hex").slice(0, 8)}` : preferredName })); }
const refName = (ref: string) => (ref.split("/").pop() ?? "Unknown").replace(/[^A-Za-z0-9_$]/g, "_");
export function schemaToType(schema: OpenApiSchema | undefined): string { if (!schema) return "unknown"; if (schema.$ref) return refName(schema.$ref); if (schema.enum?.length) return schema.enum.map((value) => value === null ? "null" : JSON.stringify(value)).join(" | "); if (schema.oneOf?.length) return schema.oneOf.map(schemaToType).join(" | "); if (schema.anyOf?.length) return schema.anyOf.map(schemaToType).join(" | "); if (schema.allOf?.length) return schema.allOf.map(schemaToType).join(" & "); const types = Array.isArray(schema.type) ? schema.type : schema.type ? [schema.type] : []; const nullable = schema.nullable === true || types.includes("null"); const type = types.find((entry) => entry !== "null"); let rendered = "unknown"; if (type === "string") rendered = "string"; else if (type === "integer" || type === "number") rendered = "number"; else if (type === "boolean") rendered = "boolean"; else if (type === "array") rendered = `Array<${schemaToType(schema.items)}>`; else if (schema.properties) { const required = new Set(schema.required ?? []); rendered = `{ ${Object.keys(schema.properties).sort().map((key) => `${JSON.stringify(key)}${required.has(key) ? "" : "?"}: ${schemaToType(schema.properties?.[key])};`).join(" ")} }`; } else if (schema.additionalProperties && typeof schema.additionalProperties === "object") rendered = `Record<string, ${schemaToType(schema.additionalProperties)}>`; else rendered = "Record<string, unknown>"; return nullable ? `${rendered} | null` : rendered; }
export function responseSchema(operation: OpenApiOperation): OpenApiSchema | undefined { const responses = operation.responses ?? {}; const code = Object.keys(responses).filter((value) => /^2\d\d$/.test(value)).sort()[0]; const content = (code ? responses[code] : responses.default)?.content ?? {}; return content["application/json"]?.schema ?? Object.values(content)[0]?.schema; }
export function requestBodySchema(operation: OpenApiOperation): OpenApiSchema | undefined { const content = operation.requestBody?.content ?? {}; return content["application/json"]?.schema ?? Object.values(content)[0]?.schema; }
