import { spawn, type ChildProcess } from "node:child_process";
import { createServer } from "node:net";
import { resolve } from "node:path";
import { loadProjectManifest } from "../project/manifest";
export type DevService = { id: string; kind: "infrastructure" | "migration" | "process"; dependencies: string[]; command: string; args: string[]; port?: number; required: boolean };
export type DevPlan = { projectDirectory: string; services: DevService[] };
export type DevProcess = Pick<ChildProcess, "pid" | "kill" | "once">;
export type DevAdapters = { spawn: (command: string, args: string[], options: { cwd: string; stdio: "inherit" }) => DevProcess; portAvailable: (port: number) => Promise<boolean>; sleep: (ms: number) => Promise<void> };
const defaultAdapters: DevAdapters = { spawn(command, args, options) { return spawn(command, args, { ...options, shell: false }); }, portAvailable(port) { return new Promise((done) => { const server = createServer(); server.unref(); server.once("error", () => done(false)); server.listen({ host: "127.0.0.1", port }, () => server.close(() => done(true))); }); }, sleep(ms) { return new Promise((done) => setTimeout(done, ms)); } };
export function topologicalServices(services: DevService[]): DevService[] { const byId = new Map(services.map((item) => [item.id, item])); const indegree = new Map<string, number>(); const dependents = new Map<string, string[]>(); for (const item of services) { indegree.set(item.id, item.dependencies.length); for (const dep of item.dependencies) { if (!byId.has(dep)) throw new Error(`Unknown dev service dependency ${dep} for ${item.id}`); const list = dependents.get(dep) ?? []; list.push(item.id); dependents.set(dep, list); } } const queue = services.filter((item) => (indegree.get(item.id) ?? 0) === 0).sort((a, b) => a.id.localeCompare(b.id)); const ordered: DevService[] = []; while (queue.length) { const item = queue.shift(); if (!item) break; ordered.push(item); for (const id of (dependents.get(item.id) ?? []).sort()) { const next = (indegree.get(id) ?? 0) - 1; indegree.set(id, next); if (next === 0) { const dependent = byId.get(id); if (dependent) { queue.push(dependent); queue.sort((a, b) => a.id.localeCompare(b.id)); } } } } if (ordered.length !== services.length) throw new Error("Development service dependency cycle detected."); return ordered; }
export function createDevPlan(projectDirectoryInput: string): DevPlan { const projectDirectory = resolve(projectDirectoryInput); const manifest = loadProjectManifest(projectDirectory); const capabilities = new Set(Object.keys(manifest.capabilities)); const services: DevService[] = [{ id: "postgres", kind: "infrastructure", dependencies: [], command: "docker", args: ["compose", "up", "-d", "postgres"], port: 5432, required: true }]; if (capabilities.has("redis") || capabilities.has("queue")) services.push({ id: "redis", kind: "infrastructure", dependencies: [], command: "docker", args: ["compose", "up", "-d", "redis"], port: 6379, required: true }); services.push({ id: "migrations", kind: "migration", dependencies: ["postgres"], command: "npm", args: ["run", "prisma:deploy"], required: true }, { id: "api", kind: "process", dependencies: ["postgres", ...(services.some((item) => item.id === "redis") ? ["redis"] : []), "migrations"], command: "npm", args: ["run", "dev"], port: 3000, required: true }); if (capabilities.has("queue")) services.push({ id: "worker", kind: "process", dependencies: ["redis", "migrations"], command: "npm", args: ["run", "worker"], required: false }); if (capabilities.has("cron")) services.push({ id: "scheduler", kind: "process", dependencies: ["migrations"], command: "npm", args: ["run", "scheduler"], required: false }); return { projectDirectory, services: topologicalServices(services) }; }
export function selectDevPlan(plan: DevPlan, options: { service?: string; noMigrate?: boolean }): DevPlan { let services = plan.services; if (options.noMigrate) { services = services.filter((item) => item.id !== "migrations").map((item) => ({ ...item, dependencies: item.dependencies.filter((dep) => dep !== "migrations") })); } if (options.service) { const byId = new Map(services.map((item) => [item.id, item])); if (!byId.has(options.service)) throw new Error(`Unknown dev service: ${options.service}`); const selected = new Set<string>(); const visit = (id: string) => { if (selected.has(id)) return; const item = byId.get(id); if (!item) throw new Error(`Missing selected dependency: ${id}`); selected.add(id); for (const dep of item.dependencies) visit(dep); }; visit(options.service); services = services.filter((item) => selected.has(item.id)); } return { ...plan, services: topologicalServices(services) }; }
function waitForExit(child: DevProcess, timeoutMs: number): Promise<number | null> { return new Promise((done, reject) => { let settled = false; const timer = setTimeout(() => { if (!settled) { settled = true; reject(new Error(`Process ${child.pid ?? "unknown"} did not exit within ${timeoutMs}ms`)); } }, timeoutMs); child.once("exit", (code: number | null) => { if (settled) return; settled = true; clearTimeout(timer); done(code); }); }); }
async function waitUntilPortOccupied(port: number, adapters: DevAdapters, timeoutMs: number): Promise<void> { const deadline = Date.now() + timeoutMs; while (Date.now() < deadline) { if (!(await adapters.portAvailable(port))) return; await adapters.sleep(100); } throw new Error(`Timed out waiting for service on port ${port}`); }
export class DevOrchestrator { private readonly children = new Set<DevProcess>(); private stopped = false; constructor(private readonly plan: DevPlan, private readonly adapters: DevAdapters = defaultAdapters) {} async start(options: { readinessTimeoutMs?: number } = {}): Promise<void> { const timeoutMs = options.readinessTimeoutMs ?? 30_000; const ports = new Set<number>(); for (const service of this.plan.services) if (service.port) { if (ports.has(service.port)) throw new Error(`Duplicate configured dev port: ${service.port}`); ports.add(service.port); if (!(await this.adapters.portAvailable(service.port))) throw new Error(`Port ${service.port} required by ${service.id} is already occupied.`); } try { for (const service of this.plan.services) { const child = this.adapters.spawn(service.command, service.args, { cwd: this.plan.projectDirectory, stdio: "inherit" }); this.children.add(child); child.once("exit", () => this.children.delete(child)); if (service.kind !== "process") { const code = await waitForExit(child, timeoutMs); if (code !== 0 && service.required) throw new Error(`${service.id} failed with exit code ${String(code)}`); } else if (service.port) await waitUntilPortOccupied(service.port, this.adapters, timeoutMs); } } catch (error) { await this.stop(); throw error; } } async stop(): Promise<void> { if (this.stopped) return; this.stopped = true; const children = [...this.children]; for (const child of children) try { child.kill("SIGTERM"); } catch {} await Promise.race([Promise.allSettled(children.map((child) => waitForExit(child, 5_000))), this.adapters.sleep(5_100)]); for (const child of [...this.children]) { try { child.kill("SIGKILL"); } catch {} this.children.delete(child); } } }
